# notifyStaff - Notifies staff members when a new request is filed.
# hideMessageIfEmpty - If true, hides the notification on login if there are no open requests.
# debug - If true, it will show information about actions performed.
# messages - Change messages shown in ReportRTS.
# mysql.enable - If true, uses MySQL instead of SQLite.
# request.max - Maximum number of requests a user may have open at the same time.
# request.delay - User has to wait this amount of seconds before filing another request.
# request.hideOffline - If set to true, hides all requests in /check from offline users.
# request.perPage - This sets the amount of requests that should be shown on each page.
# request.nag - If above 0 (minutes), nag the online staff members about open requests.

notifyStaff: true
hideMessageIfEmpty: false
debug: false

request:
  delay: 60
  max: 5
  hideOffline: false
  perPage: 5
  nag: 5

mysql:
  enable: false
  hostname: 'localhost'
  port: 3306
  database: 'minecraft'
  username: 'username'
  password: 'password'

messages:
  generalPermissionError: '%yellow%You need permission to do that: {0}'
  generalInternalError: '%red%An error occurred. Reference: {0}'
  generalOpenRequests: '%green%There are {0} open requests. Type /check to see them.'
  generalNoRequests: '%white%There are no requests at this time.'
  generalRequestNotFound: '%red%Request #{0} was not found.'
  banUser: '%gold%{0} has banned {1} from filing requests.'
  unbanUser: '%gold%{0} has unbanned {1} from filing requests.'
  checkNoRequests: '%gold%There are no requests right now.'
  claimRequest: '%gold%{0} is now handling request #{1}.'
  claimNotOpen: '%red%You may only claim open requests.'
  claimUser: '%gold%{0} is now handling your request.'
  claimText: '%gold%Request text: %yellow%{0}'
  unclaimReqMod: '%gold%{0} is no longer handling request #{1}.'
  unclaimReqSelf: '%gold%Request #{0} has been unclaimed.'
  unclaimNotClaimed: '%red%You may only unclaim requests that are claimed.'
  unclaimUser: '%gold%{0} is no longer handling your request.'
  unclaimText: '%gold%Request text: %yellow%{0}'
  completedReq: '%gold%Request #{0} was completed by {1}.'
  completedUser: '%gold%{0} completed your request.'
  completedUserOffline: '%gold%One of your requests have been completed.'
  completedText: '%gold%Request text: %yellow%{0} %gold%Comment: %yellow%{1}'
  holdRequest: '%gold%Request #{0} was put on hold by {1}'
  holdNoRequests: '%gold%There are no requests on hold right now.'
  holdUser: '%gold%Your request was put on hold by {0}'
  holdText: '%gold%Request text: %yellow%{0} %gold%Reason: %yellow%{1}'
  broadcastMessage: '%white%[%red%Mod-Broadcast%white%] %red%{0}: %green%{1}'
  modreqFiledUser: '%gold%Your request has been filed. A staff member should be with you soon.'
  modreqFiledMod: '%green%A new request has been filed by {0}, id assigned #{1}.'
  modreqTooManyOpen: '%red%You have too many requests open, please wait before filing more.'
  modreqTooFast: '%red%You need to wait {0} seconds before attempting to file another request.'
  modlistMessage: '%aqua%Staff online: %yellow%{0}'
  modlistMessageSeparator: '%yellow%, '
  modlistNoMods: '%yellow%There are no staff members online.'
  reopenedRequest: '%gold%{0} has reopened request #{1}'
  reopenedRequestSelf: '%gold%Request #{0} has been reopened.'
  teleportToRequest: '%blue%Teleported to request #{0}.'